# Generated by Django 5.0.2 on 2024-02-20 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('adminName', models.TextField(max_length=20)),
                ('adminPass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentorId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MentorName', models.TextField(max_length=50)),
                ('mentorPass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('studentName', models.TextField(max_length=20)),
                ('studentPass', models.CharField(max_length=20)),
                ('mentorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('reportType', models.TextField(max_length=20)),
                ('reportProg', models.TextField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('mentorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.mentor')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.student')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report', models.TextField(blank=True, null=True)),
                ('date', models.DateField(max_length=20)),
                ('time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('mentorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.mentor')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.student')),
            ],
        ),
    ]
