# Generated by Django 5.0.2 on 2024-02-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='StudentAddress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
