# Generated by Django 5.0.2 on 2024-02-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0002_student_studentaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentNo',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
