# Generated by Django 5.0.2 on 2024-02-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0004_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentorNo',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentorSubject',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Studentcourse',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
